### ISSUE TITLE
why show WSL2 setup via a "Next" button after I just set up for Mac?

### ISSUE THREAD

**Issue by brigj1** [learn-co-curriculum/phase-0-wsl2-env-introduction#3]
### Canvas Link

https://learning.flatironschool.com/courses/5506/quizzes/27354

### Concern

I have just finished with setup of my Mac.
Clicking 'Next' to go to the next lesson takes me to:
Introduction to Windows Subsystem for Linux (WSL2) Environment Setup
https://learning.flatironschool.com/courses/5506/pages/introduction-to-windows-subsystem-for-linux-wsl2-environment-setup?module_item_id=371013

This doesn't seem relevant for me. 

### Suggested Changes

I'm thinking "Next" from my Mac setup "1-Question" results page should take me elsewhere (not the WSL2 setup page.)

**Comment by professor-ben** [comment]
Hi Brigham,

Thank you for your feedback. Unfortunately, we cannot modify the functionality of the "Next" button in Canvas- it always goes to the next published page or module.

We do include a note at the beginning of both setup modules informing students of their relevance to their OS. If you see a note like that in the future, you can return to the course "Home" and skip ahead to the next relevant page.

Thanks,
Ben
